# Generated by Django 6.1.1 on 2026-09-15 23:03

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_avatar_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="banner",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="banners/"
            ),
        ),
    ]
