# Generated by Django 6.1.1 on 2026-09-22 21:32

import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freebies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freebie',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='userfreebie',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='freebie',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_freebies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='freebie',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='freebies/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='vendors/'),
        ),
    ]
