# Generated by Django 6.1.1 on 2026-09-24 19:06

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freebies', '0002_add_freebie_created_by'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_vendor_name_case_insensitive'),
        ),
    ]
