# Generated by Django 6.1.1 on 2026-09-15 23:03

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="banner",
            field=imagekit.models.fields.ProcessedImageField(
                blank=True, null=True, upload_to="conventions/banners/"
            ),
        ),
    ]
